[project]
name = "autogen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.8"
dependencies = [
    "autogen-agentchat[jupyter-executor]~=0.2",
    "docker>=7.1.0",
    "ipykernel>=6.29.5",
    "ipynb>=0.5.1",
    "jupyter>=1.1.1",
    "jupyter-kernel-gateway>=3.0.1",
    "openai>=1.66.3",
    "pip>=25.0.1",
    "pyautogen>=0.8.1",
    "python-dotenv>=1.0.1",
]
